image: ubuntu:24.04
pipelines:
  custom:
    custom-deploy:
      - variables:
        - name: SSH_PORT
          default: "22"
      - step:
          script:
            - ssh -p $SSH_PORT $SSH_TARGET
            - whoami