export {default as HomePage} from "./Homepage"
export {default as AboutPage} from "./AboutPage"
export {default as News} from "./News"
export {default as PageNotFound} from "./PageNotFound"
export {default as FaqPage} from "./FaqPage"
export {default as PrivacyPage} from "./PrivacyPage"
export {default as TermsPage} from "./TermsPage"
export {default as ProductsPage} from "./ProductsPage"