export {default as Faq} from "./Faq"
export {default as UserNavbar} from "./UserNavbar"
export {default as UserCard} from "./UserCard"
export {default as InsideBanner} from "./InsideBanner"
export {default as Footer} from "./Footer"
export {default as Partners} from "./Partners"